algo = input("Digite algo: ")
print ("O dado, {}, é da classe: {}".format(algo, type(algo)))
print("Informações:")
print ("O dado é um número:" ,(algo.isnumeric())) 
print ("O dado é uma letra:" ,(algo.isalpha()))   
print ("O dado é um espaço vazio:" ,(algo.isspace()))   
print ("O dado é uma letra/palavra ou números:" ,(algo.isalnum()))  
print ("O dado possui apenas letras maiusculas:" ,(algo.isupper()))   
print ("O dado possui apenas letras minusculas:" ,(algo.islower()))   
print ("O dado possui 1° letra maiuscula e resto minuscula:" ,(algo.istitle()))