nome = input("Digite seu nome: ")
bairro = input("Digite seu bairro: ")
estado = input("Digite seu estado: ")
salario = float(input("Digite seu salário:"))
print("")
print("Nome:",nome)
print("Bairro:",bairro)
print("Estado:",estado)
print("Salário bruto: R${}, salário descontado: R${:.2}".format(salario, salario*0.80))